language: node_js
dist: bionic
# test officially supported NodeJS versions (https://nodered.org/docs/faq/node-versions) except 8.x (no longer maintained) and latest stable
node_js:
#  - 10
#  - 12
#  - 14
  - 16
  - 18
# - lts/*

# "npm test" runs tests in watch mode
script: npm run test-build

after_success: npm run coverage